apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: 
    - "--destination=hachikoapp/kaniko-demo-image:latest"
    volumeMounts:
      - name: app-files
        mountPath: /workspace
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: app-files
      hostPath:
        path:  /home/william/workspace/companies/insightsoftware/kaniko-demo # Must exist in the Node Group
        type: Directory
    - name: kaniko-secret
      secret:
        secretName: registry-credentials
        items:
          - key: .dockerconfigjson
            path: config.json

