# If pulling from Private Repository

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=Dockerfile"
    - "--context=git://github.com/williammunozr/kaniko-demo.git"
    - "--destination=hachikoapp/kaniko-demo-image:latest"
    env:
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: git-token
          key: GIT_TOKEN
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: registry-credentials
      items:
        - key: .dockerconfigjson
          path: config.json

# kubectl create secret generic git-token --from-literal='GIT_TOKEN=<your-token>'
